config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  
  resources :events
  # Allows for routes such as users/5/events
  devise_for :users
  get 'users/:id/events' => 'events#user_events' , as: :user_events
  get 'users/sign_out' => 'home#index'
  #get 'events/:id' => 'events#show'
  #get 'events/new' => 'events#new'
  get 'events/:id/subscribe' => 'events#subscribe', as: :events_subscribe
  get 'events/category/:id' => "events#category"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "creator_id"
    belongs_to :category, foreign_key:"category_id", optional: true
    
    has_and_belongs_to_many :attendees, class_name: "User"
  
	validates :title, :description, :date, :address, presence: true
	validates :title, uniqueness: true, length: { maximum: 55 }
	validates :image, presence: false #Pour seed
	mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable,
  attr_accessor :login
 has_many :created_events, class_name: "Event", foreign_key: "creator_id"
 has_and_belongs_to_many :attended_evts, class_name:"Event"
                          
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable
         
  validates :username, presence: true, uniqueness: {case_insensitive: false}, format: {with: /\A[a-zA-Z0-9_\.]*\z/}

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login) 
      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else 
      where(conditions.to_hash)
    end
  end
  
  
  # ======== AVATAR UPLOAD =========
  
  mount_uploader :avatar, AvatarUploader
   # User Avatar Validation
  validates_integrity_of  :avatar
  validates_processing_of :avatar
 
  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end
    
  #==================================
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :configure_devise_parameters, if: :devise_controller?
    
    protected
    
    def configure_devise_parameters
      
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache, :remove_avatar) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache, :remove_avatar) }
    
    end 


end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :find_event, only:[:show]
  before_action :event_params, only:[:create]
  
  def index
    @users = User.all
    @events = Event.all
  end
  
  def show
  end
    
  def new 
    @event = Event.new
  end 
  
  def create 
      @event = Event.new(event_params)
      @event.creator_id = current_user.id
    
        respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Votre évenement a bien été créé' }
      else
        format.html { render :new }
      end
    end
  end 
  
  def creator 
    @creator = User.find(params[:id])
    @events = Event.where(creator_id: @creator.id)
  end 
  
  private 
  
  def find_event 
    @event = Event.find(params[:id])
  end
  
  def event_params
    params.require(:event).permit(:title, :description, :address, :date)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	  skip_before_action :verify_authenticity_token
 	  before_action :find_event, only:[:show, :subscribe, :edit,  :update]
  	before_action :event_params, only:[:create, :edit, :update]
  	before_action :weekend, only:[:index]
  
  def index
    @users = User.all
		@events = Event.order('date asc')
		@concerts = Event.where(category_id: 1).limit(4)
  end
  
  def show
		@attendees  = @event.attendees.limit(6)
		@other_events_by_creator = Event.where('creator_id' => @event.creator_id).where("id != ?", @event.id).limit(3) #Trois suggestions d'evenements par le même organisateur  
		@maps_api_key = ENV['MAP_API_KEY']
  end
    
  def new 
    @event = Event.new
  end 

  def create 
      @event = Event.new(event_params)
      @event.creator_id = current_user.id
    
        respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Votre évenement a bien été créé' }
      else
        format.html { render :new }
      end
    end
  end 

  def edit
  end 
  
  def update
    if @event.update(article_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def user_events
    @user = User.find(params[:id])
	  @events = Event.where(creator_id: @user.id).order('date asc').paginate(:page => params[:page], :per_page => 16)
  end 

  def subscribe
    @event.attendees << current_user
		flash[:notice] = "Vous vous êtes bien inscrit(e) à l'évenement \" #{@event.title } \""
		redirect_to @event 
  end
  
  def category
	 @events = Event.where(category_id: params[:id]).paginate(:page => params[:page], :per_page => 16)
	 @category = Category.find(params[:id])
  end
 #------helpers------

 

 private 		# ------------------------------------------- 
  
  def find_event 
    @event = Event.find(params[:id])
  end
  
  def event_params
    params.require(:event).permit(:title, :description, :address, :date, :time, :category_id, :image,  :image_cache, :remove_image)
  end

  def weekend
	events = Event.all 
	@weekend = []
	events.each do |e|
		if (e.date.wday == 6 || e.date.wday ==7) && (e.date < Date.today + 7)
			@weekend << e 
		end 
	end
	@weekend
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :find_event, only: [:show]
  def index
	@events = Event.all
	 @user = User.all

  end
  
  def show
  end
    
  def new 
    @event = Event.new
  end 
  
  def create 
  end 
  
  private 
  
  def find_event 
    @event = Event.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_time(str)
    return   "#{str.split('')[0..1].join('')}h#{str.split('')[3..4].join('')}"
  end

  def formatted_date(date)
    return date.strftime("%d/%m/%Y")
  end

  def has_image(param)
	return !param.image.blank?
  end 
end

app/helpers/event_helper.rb
module EventHelper
  def some_events_from_category(limit, id)
	return Event.where(category_id: id)
  end 
  
   def display_default_image_show(param)
	  	if param.image?
	  	return "param.image.thumb.url"
	  	else 
	  	return "https://source.unsplash.com/random/#{rand(800..820)}x#{rand(620..650)}"
	  	end 
  end
  
  def display_default_image(param)
	  	if param.image?
	  	return "param.image.thumb.url"
	  	else 
	  	return "https://source.unsplash.com/random/#{rand(400..420)}x#{rand(420..450)}"
	  	end 
  end
end

app/helpers/home_helper.rb
module HomeHelper

	def popular(events, minimum)

			popular_events = []
			
				events.each do |event|
					if event.attendees.count > minimum
						popular_events << event 
					end 
			end
			return popular_events
			
	end 
		
end

app/views/event/new.html.erb
<%= form_for @event, url: {action: "create"}, html: {class: "event-f"} do |f| %>
    
    <!-- ERREURS ?-->
    
    <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>Il y a <%= pluralize(@event.errors.count, "erreur") %> dans la création de cet évenement</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <!-- FIN ERREURs -->
    
    <p><%= f.label(:nom)%></p>
    <p><%= f.text_field(:title, size:50, required: true) %></p> 
   
    <p><%= f.label(:date)%></p>
    <p><%= datetime_local_field(:event, :date, required: true) %></p>
   
    <p><%= f.label(:adresse)%></p>
    <p><%= f.text_field(:address, size:50, required: true) %> </p>
    
    <p><%= f.label(:description)%></p>
    <p><%= f.text_area(:description, cols:60, rows:8, required: true)%></p>
    
    <p><%= f.submit "Create" %></p>
<% end %>

<!-- Gérer les erreurs -->

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true, html: {class: "event-f"})  do |f| %>
    
    <!-- ERREURS ?-->
    
    <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>Il y a <%= pluralize(@event.errors.count, "erreur") %> dans la création de cet évenement</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <!-- FIN ERREURs -->
    
    <p><%= f.label(:nom)%></p>
    <p><%= f.text_field(:title, size:50, required: true) %></p> 
   
    <p><%= f.label(:date)%></p>
    <p><%= f.date_field(:date,  min: Date.today, required: true) %></p>

    <p><%= f.label(:heure)%></p>
    <p><%=f.text_field(:time, type:"time") %></p>
    
    <p><%= f.label(:adresse)%></p>
    <p><%= f.text_field(:address, size:50, required: true) %> </p>
    
    <p><%= f.label(:description)%></p>
    <p><%= f.text_area(:description, cols:60, rows:8, required: true)%></p>
    
    <p>
    <%= f.select(:category_id, options_for_select(
    [
      ['Concerts', 1],
      ['Expos', 2],
      ['Spectacles', 3],
      ["Sport", 4],
      ["Loisirs", 5],
      ["Nature", 6]
      ], 5)) %>
      </p>

	<p>	<%= f.label :image %>
	<p>	<%= f.file_field :image %><br>
	<p>	<%= f.hidden_field :image_cache %></p>    
  <p><%= f.submit "Create" %></p>

<% end %>

app/views/events/_maps.html.erb
<script>

		let eventAddress = document.getElementById("event--address").innerText.split(" ").join('')
		let mymap
		const mapsApiKey = $("div[data-api]").data('api')
		const geoUrlPartOne="https://maps.googleapis.com/maps/api/geocode/json?address="
		const geoUrlPartTwo="&key="
		const geoDynamicUrl = [geoUrlPartOne, eventAddress, geoUrlPartTwo, "AIzaSyDbwbtPQ1ly2uCArp6RN40VEpPuR1WJQo0" ].join('')
		let latitude = null
		let longitude = null
		
// Callback de la requête à google maps

	function initMap() {		
				const coordinates = {lat: latitude, lng: longitude};
				
				// CARTE
				mymap = new google.maps.Map(document.getElementById('map'), {
				zoom: 11,
				center: coordinates
				})
				// MARKER
				const marker = new google.maps.Marker({
				position: coordinates,
				map: mymap
				});
			}
	
// API DE GEOLOCALISATION (eventAddress => coordonnées (lat, lng))		
			fetch(geoDynamicUrl)
			
			.then(function(response) {
			
			console.log('geo start');
			return response.json();

			})
			.catch(error => console.log('geo brut error: ' + error))

			.then(function(myJson) {
			console.log(myJson)
				latitude = myJson.results[0].geometry.location.lat
				longitude = myJson.results[0].geometry.location.lng
				console.log("geo end ", latitude , longitude)
				//	console.log("latitude en " + typeof latitude  + "longitude en " +  typeof longitude);
			})
			.catch(error => console.log('geo traité ' + error))
			
// API GOOGLE MAPS 
			.then(function (){
			
				const  mapsUrl = "https://maps.googleapis.com/maps/api/js?key="+ "AIzaSyDbwbtPQ1ly2uCArp6RN40VEpPuR1WJQo0" +  "&callback=initMap"
				let scriptElt = document.createElement('script')
				scriptElt.setAttribute('src', mapsUrl)
				body = document.getElementsByTagName("body")[0]
				body.appendChild(scriptElt)
		})
			.catch(error => console.log('generate script :' + error))
 // turbolinks - end 
 </script>

app/views/events/category.html.erb
<div class="content--wrap">
	<div class="category--nav">
		<div class="container">
				<h1 class = "section--title"><%=@category.title %></h1>
		</div>
	</div>
<div class="grid--outer">

		<div class="grid--wrapper">
			<% @events.each do |event| %>
								
				<div class=" event">
						<div class="event--details">
										<a href="/events/<%=event.id%>" class="event--title"><%= event.title %></h2></a>
						<p>Le <span class="date"><%= formatted_date(event.date)%></span>  à <span class="date"> <%= formatted_time(event.time) %></span>
											
											<p class = "event--creator"> Créé par <a href="/users/<%=event.creator_id%>/events">"<%= event.creator.username %>"</p></a>
											
							</div>

							<!--IMAGE SI FOURNIE -->
			
							<div class="event--pic">												
										<%= image_tag "#{display_default_image(event)}"%>
											<button>S'incrire</button>
								</div>
				
				</div>
			<% end %>
		</div>
		
	</div>  <!--grid outer end-->
	<%= will_paginate @events %>

</div>

app/views/events/creator.html.erb
<div class="container">
    
    <% if !@creator.avatar.file.nil? %>
        <h1><%=@creator.username%></h1>
        <p><%=image_tag(@creator.avatar.thumb.url)%></p>
        <% else %>
         <p><%=image_tag("avatar_default.jpeg")%></p>
    <% end %>

    <% @events.each do |event| %>
      <% @description = event.description.to_s %>
              
      <div class="event">
          <div class="event-details">
                  <a href="/events/<%=event.id%>"><%= event.title %></h2></a>
                    <p>Le <%= formatted_date(event.date)%> à  <%= formatted_time(event.time) %>
               
              <!-- Gestion de la longueur de la description (extrait si > 300 caractères) -->            
                    <p><%= @description.truncate(450, separator:' ') %></p>
              <!-- Gestion de la longueur de la descriptions - fin -->
                     </div>
                <% if has_image(event)%>      
                       <div class="event-pic">   
                       
                                <%= image_tag(event.image_url)%>
                                <button>S'incrire</button>
                    
                     </div>
                <% end %>
                    </div>
        <% end %>
    </div>

app/views/events/edit.html.erb
<div class="wrap">
<% if current_user.avatar %>
<p><%= current_user.avatar %></p>
<% end %>
<%= render "form" %>
</div>	

app/views/events/index.html.erb
	<!-- bandeau  (absolute)-->
		<!-- bandeau -->
	<div class="content--wrap">

	<!-- week-end  -->
		<div class="section--head " id="section--head--first" >
			<h1 class = "section--title"> Ce Week-End</h1>
		</div>

	
	<div class="grid--outer">
		<div class="grid--wrapper">
				
				<% @weekend.each do |event| %>
			
			<div class="event">
			<a href="/events/<%=event.id%>">
				<div class="event--details">
					<h2 class="event--title"><%= event.title %></h2>
				</a>
						<p>Le <span class="date"><%= formatted_date(event.date)%></span>  à <span class="date"> <%= formatted_time(event.time) %></span>
						<p class ="event--address"><%= event.address.titleize %></p>

						<p class = "event--creator"> Créé par <a href="/users/<%=event.creator_id%>/events">"<%= event.creator.username %>"</p></a>
				</div>

								<!--IMAGE -->
				
				<div class="event--pic">
							<a href="/events/<%=event.id%>">							
								<%= image_tag "#{display_default_image(event)}" %>
							</a>
				</div><!--IMAGE  fin -->
			</div> <!-- event fin -->
				<% end %>
		</div> <!--section-wrapper fin -->
	</div>
		<!-- week end fin /concerts  debut-->




			<div class="section--head">
				<h1 class = "section--title">Concerts</h1>
			</div>

		<div class="grid--outer">
			<section class="grid--wrapper">
				<%  @concerts.each do |event|%>
							
					<div class="event">
						<a href="/events/<%=event.id%>">
							<div class="event--details">
									<a href="/events/<%=event.id%>" class="event--title"><%= event.title %></h2></a>
										<p>Le <span class="date"><%= formatted_date(event.date)%> </span>à <span class="date"><%= formatted_time(event.time)%> </span><p>
										<p class ="event--address"><%= event.address.titleize %></p>
											
										<p class="event--creator"> Créé par <a href="/users/<%=event.creator_id%>/events">"<%= event.creator.username %>"</p></a>
						</a>
								</div>
							
								<!--IMAGE -->
				
							<div class="event--pic">
								<a href="/events/<%=event.id%>">
									<%= image_tag "#{display_default_image(event)}" %>			
								</a> <!--IMAGE  fin-->
							</div>
							
					</div>
						
			

				<% end %> <!-- events from category fin-->
			<section><!-- category fin-->
		</div>				<!--wrap fin -->
	</div>

app/views/events/new.html.erb
<div class="content--wrap">
<div class="form--title"><h2>Créer un évènement</h2></div>
	<%= render "form" %>
</div>

app/views/events/show.html.erb
<div class="content--wrapper">
	<div class="show--wrapper"> 
			
			<!-- début de la présentation de l'évenement!-->
		
		<section class="show--wrapper--top"> 
				<!-- image -->
			<div class="event--picture">
				<p><%= image_tag "#{display_default_image(@event)}" %></p>
			</div>
				<!-- image end -->
			<div class="event--info">

				<h1 class="show--event--title"><%= @event.title %></h1>
						<p>Le <span class="date"><%= formatted_date(@event.date)%></span>  à <span class="date"> <%= formatted_time(@event.time) %></span>
						<p id="event--address"><%= @event.address %></p>
						<p class="event--creator">Créé par <a href="/users/<%=@event.creator_id%>/events"><%= @event.creator.username %></a></p>

				<!-- Inscription start-->      
				<% if user_signed_in?%>
										<%if @event.attendees.include?(current_user) %>
												<p><img src="https://s3-eu-west-1.amazonaws.com/zclmkavatar/images/checked.svg"height="32" width="32"> </img>Vous êtes inscrit à cet évenement</p>
										<%elsif current_user.id == @event.creator_id%>
												<p>Vous êtes le créateur de l'évenement</p>
										<%else%>
										<%= link_to "Inscription", events_subscribe_path, id: "inscription" %>
										<%end%>
						<%end%>
					<!-- Inscription end-->
			</div> <!-- event-info end -->
					
		</section>	
	
			
		<section class="show--wrapper--middle">

					<div class="description">
						<h3 class="title">Description </h3>
						<p>
							<%= @event.description %>
						</p>        
					</div>
						<h3><%= @event.attendees.count %> inscrit(s) dont:</h3>
					<div class="attendees">
						
						<% @attendees.each do |attendee|%>
						
						<div class="attendee">
							<p><%= image_tag "#{ attendee.avatar.thumb.url}" %></p>
						</div>
							
						<% end %>	
					</div>
			<!--  						 MAP based on event.address 				- -->
			<h3 class="title">Carte:</h3>
					<div id="map" data-api="<%= @maps_api_key %>">
					
					</div>
			<h3 class="title">Quelques évenements par le même organisateur</h3>
			<div class="grid--outer--show">
				<div class="grid--wrapper">
								<% @other_events_by_creator.each do |event| %>
						
						
						<div class="event">
							<a href="/events/<%=event.id%>">
								<div class="event--details">
									<h2 class="event--title"><%= event.title %></h2>
								</a>
										<p>Le <span class="date"><%= formatted_date(event.date)%></span>  à <span class="date"> <%= formatted_time(event.time) %></span>
										<p><%= event.address.titleize %></p>
	
										<p class = "event--creator"> Créé par <a href="/users/<%=event.creator_id%>/events">"<%= event.creator.username %>"</p></a>
								</div>
	
												<!--IMAGE -->
								
								<div class="event--pic">
											<a href="/events/<%=event.id%>">							
												<%= image_tag "#{display_default_image_show(event)}" %>
											</a>
								</div><!--IMAGE  fin -->
							</div> <!-- event fin -->
								<% end %>
					
					</div> <!--section-wrapper fin -->
				</div> <!--suggestions end -->
			</div> <!--suggestions--wrapper--end-->
				</div>
			</div> <!-- suggestions start-->
				
			</section> <!--show wrapper middle end-->
		</div> <!-- show wrapper fin-->
		

			<%= render  "maps" %>
		</div>
	
</div><!-- content wrapper end-->

app/views/home/index.html.erb
<!-- Carousel ------------------------------------------------------------------>
<div class="carousel carousel--img--one">

				<div class="home--welcome--box ">
					<h2>Organisez et invitez-vous <br> à des évenements près de chez vous!</h2></p>
						  <div >
						<% if user_signed_in? %>
                        	<p> <%= link_to 'Organiser un évenement', new_event_path, id: 'new--event'%></p>
						<% else %>
							<p><%= link_to 'Se connecter', new_user_session_path, id:"button--connect"%></p>
						<% end %>
						</div>

<%#= button_to("Forgot Password", new_user_password_path, id:"forget-password", class:"forget-password") %>
			
</div>	
<!-- Carousel fin ------------------------------------------------------------------>

app/views/shared/_header.html.erb
  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand top--sitename" href="/">Bribe</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to  "Evenements",  events_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              	Catégories
              	 <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a class="top--item" href="/events/category/1">Concerts</a></li>
								<li><a class="top--item" href="/events/category/2">Expos</a></li>
								<li><a class="top--item" href="/events/category/3">Spectacles</a></li>
								<li><a class="top--item" href="/events/category/4">Sport</a></li>
								<li><a class="top--item" href="/events/category/5">Loisirs</a></li>
								<li><a class="top--item" href="/events/category/6">Nature</a></li>
              </ul>
            </li>
          </ul>
          
        <% if user_signed_in?%>
        <ul class="nav navbar-nav navbar-right">
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              	 <%=image_tag(current_user.avatar.thumb.url)%>
              	 <span class="caret"></span>
              </a>
		          <ul class=" dropdown-menu">
		           	<li><%= link_to  "Editer mon profil", edit_user_registration_path, class:"top--item" %></li>
								<li><a class="top--item" href="/users/<%= current_user.id %>/events">Mes evenements</a></li>    
								<li><%= link_to  "Déconnexion", destroy_user_session_path, method: :delete, class:"top--item"%></li>
		          </ul>
          </li>
         </ul>
        <%end%>
          				
          				
				
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    

    <!--
    <nav class="nav--top navbar navbar-fixed-top">
   
        <div class="navbar-header">
      
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="nav-item "><a class="top--item dropdown" href="/">Home</a></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle top--item" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Catégories <span class="caret"></span></a>
                <ul class="dropdown-menu drop--ul">
									
									
                </ul>
             </li>
         	</ul>
<!-- AVATAR --><!--
		
		
			


       <!--/.nav-collapse --><!--
		 </div>
    </nav>
-->

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand top--sitename" href="/">Bribe</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to  "Evenements",  events_path %></li>
            <li >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              	Catégories
              	 <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a class="top--item" href="/events/category/1">Concerts</a></li>
								<li><a class="top--item" href="/events/category/2">Spectacles</a></li>
								<li><a class="top--item" href="/events/category/3">Sport</a></li>
								<li><a class="top--item" href="/events/category/4">Loisirs</a></li>
								<li><a class="top--item" href="/events/category/5">Nature</a></li>
              </ul>
            </li>
          </ul>
          
        <% if user_signed_in?%>
        <ul class="nav navbar-nav navbar-right">
           <li>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              	 <%=image_tag(current_user.avatar.thumb.url)%>
              	 <span class="caret"></span>
              </a>
		          <ul class=" dropdown-menu">
		           	<li><%= link_to  "Editer mon profil", edit_user_registration_path, class:"top--item" %></li>
								<li><a class="top--item" href="/users/<%= current_user.id %>/events">Mes evenements</a></li>    
								<li><%= link_to  "Déconnexion", destroy_user_session_path, method: :delete, class:"top--item"%></li>
		          </ul>
          </li>
        </ul>
        <%end%>
          				
          				
				
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    

    <!--
    <nav class="nav--top navbar navbar-fixed-top">
   
        <div class="navbar-header">
      
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="nav-item "><a class="top--item dropdown" href="/">Home</a></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle top--item" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Catégories <span class="caret"></span></a>
                <ul class="dropdown-menu drop--ul">
									
									
                </ul>
             </li>
         	</ul>
<!-- AVATAR --><!--
		
		
			


       <!--/.nav-collapse --><!--
		 </div>
    </nav>
-->